---

# May be the name of any adapter in source/adapters
adapter: base

# An array of any language code in source/languages
languages: [cs, de-DE, en, es, fr, it, nl]

# An array of names of players found in source/players
players: [img]

# YES to include support for CSS selectors, NO to decline
css_support: YES

# YES to compress the code, NO to use the source code
compress: YES

# The directory to output the build to
target: build
